### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Lucassifoni** [TeomanDavid/HadCRUT3-Visualization#15]
Hello,
Your demo is really interesting, and I see that you said in a Medium post something along the lines of "feel free to play with the code". I'm building a temperature map for a client and would like to take inspiration from your code because the effect we want to achieve is quite similar. Would that be okay ?
Since the repository does not have a license in it, I prefered to ask.
Have a nice day,
Lucas

**Comment by TedYav** [comment]
Hi Lucas,

Thank you for asking! Please go ahead :)

Thanks,
Ted

**Comment by TedYav** [comment]
No need to provide credit or anything, but if there's a convenient place to
put a link and you'd like to, feel free to link to the repo.

Take care,
Ted

**Comment by Lucassifoni** [comment]
Hello,
I ended up using another way to solve this problem, but thank you for your past answer.
Best regards,
Lucas
